POST https://localhost:7172/api/User/VerifyJwt?username=string
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4ZmYyYWU0Yi01MTRhLTQxZDUtODkyYy1kNzU1NzQwZmQzMmMiLCJzdWIiOiJNZXJjIiwiZW1haWwiOiJNZXJjIiwidXNlcmlkIjoiOWZlYTE0N2ItNjFjZC00NTAxLTgxNGYtMDg1NWYxMGIzMjU3IiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzE3MiIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcxNzIiLCJleHAiOjE3MjU3ODI2ODIsImlhdCI6MTcyNTc3OTA4MiwibmJmIjoxNzI1Nzc5MDgyfQ.91-qqhUCeB7bWwjxWEVyG9dHeftuQYyaZEXwNxIIaA0
