GET https://localhost:8080/api/Drive/GetFiles/a4342f39-36d7-438b-92f0-8ffec2d103db
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyYWFmNWNiYi1iNTMyLTRmYWItYjU0ZC1jMGIxMmNhMWE3NTgiLCJzdWIiOiJPYWlzaFFhemkiLCJlbWFpbCI6Ik9haXNoUWF6aSIsInVzZXJpZCI6ImRmM2I2M2RiLWEwOTUtNGQ5MC04M2NiLTUzNDIyNTc1NWU0YSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjgwODAiLCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MDgwIiwiZXhwIjoxNzI2NzcwMTUwLCJpYXQiOjE3MjY3NjY1NTAsIm5iZiI6MTcyNjc2NjU1MH0.iau2MivKlW0YTfqujxIWoE-oAGX9HB0YExsUHb1Vit8

###
#POST https://api-454002136558.us-central1.run.app/api/User/Register
#Content-Type: application/json
#
#{
#  "email": "oaishazher@gmail.com",
#  "username": "OaishQazi",
#  "password": "QaziOaish",
#  "confirmPassword": "QaziOaish"
#}

