POST https://api-454002136558.us-central1.run.app/api/User/Register
Content-Type: application/json

{
  "email": "oaishazher@gmail.com",
  "username": "OaishQazi",
  "password": "QaziOaish",
  "confirmPassword": "QaziOaish"
}
