import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";
import {NavBar} from "@/components/navbar/NavBar";
import {SliderProvider} from "@/components/shared/Provider";
import AuthMiddleWare from "@/components/auth/AuthMiddleWare";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Proto Drive</title>
            <link rel="icon" href="/favicon.png" sizes="any"/>
        </head>
        <body className={inter.className}>
        <main>
            <SliderProvider>
                <AuthMiddleWare/>
                <NavBar/>
                {children}
            </SliderProvider>
        </main>
        </body>
        </html>
    );
}
